
services:
  
  web:
    build:
        .
    ports:
      - 8000:8000
    volumes:
      - ./:/hookly/
    command: ./entrypoint.sh
  db:
    image: postgres:15-alpine
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:

